export { default as GermanyIcon } from './country-icons/germany'
export { default as SwedenIcon } from './country-icons/Sweden'
export { default as BritainIcon } from './country-icons/Britain'
export { default as ThailandIcon } from './country-icons/Thailand'
export { default as ChevronDownIcon } from './ChevronDown'
export { default as CopyrightIcon } from './CopyRight'
export { default as LinkedinIcon } from './social-icons/Linkedin'
export { default as InstagramIcon } from './social-icons/Instagram'
export { default as XIcon } from './social-icons/X'
export { default as YoutubeIcon } from './social-icons/Youtube'
export { default as CloseIcon } from './CloseIcon'
export { default as TickIcon } from './TickIcon'
export { default as GoogleIcon } from './GoogleIcon'
export { default as FacebookIcon } from './FacebookIcon'
export { default as AlertIcon } from './menu/alert'
export { default as UserIcon } from './menu/user'
export { default as CircledArrowIcon } from './CircledArrowIcon'
// dashboard
export { default as EnvelopeIcon } from './dashboard/EnvelopeIcon'
export { default as HomeIcon } from './dashboard/HomeIcon'
export { default as QuoteDollarIcon } from './dashboard/QuoteDollarIcon'
export { default as AdIcon } from './dashboard/AdIcon'
export { default as WrenchIcon } from './dashboard/WrenchIcon'
export { default as CommentsIcon } from './dashboard/CommentsIcon'
export { default as InventoryIcon } from './dashboard/InventoryIcon'
export { default as CircledDollarIcon } from './dashboard/CircledDollarIcon'
export { default as BookingIcon } from './dashboard/BookingIcon'
export { default as CalenderIcon } from './dashboard/CalenderIcon'
export { default as SettingsIcon } from './dashboard/SettingsIcon'
export { default as ShieldIcon } from './dashboard/ShieldIcon'
export { default as BellIcon } from './dashboard/BellIcon'
export { default as HeadphoneIcon } from './dashboard/HeadphoneIcon'
export { default as ExitIcon } from './dashboard/ExitIcon'
export { default as IconTickBanner } from './dashboard/icon-tick-banner'
export { default as IconTickClipBoard } from './dashboard/icon-tick-clipboard'
// dashboard >>> messages
export { default as PlusIcon } from './dashboard/messages/PlusIcon'
export { default as QuarterCircleIcon } from './dashboard/messages/QuarterCircleIcon'
export { default as QuoteIcon } from './dashboard/messages/QuoteIcon'
export { default as OfficialIcon } from './dashboard/messages/OfficialIcon'
export { default as BigCloseIcon } from './dashboard/messages/BigCloseIcon'
export { default as ClockwiseIcon } from './dashboard/messages/ClockwiseIcon'
export { default as MassageIcon } from './dashboard/messages/MassageIcon'
export { default as TimeIcon } from './dashboard/messages/TimeIcon'
export { default as PriceTagIcon } from './dashboard/messages/PriceTagIcon'
export { default as SendIcon } from './dashboard/messages/SendIcon'
export { default as PaperClipIcon } from './dashboard/messages/PaperClipIcon'
export { default as Clockwise2Icon } from './dashboard/my-ads/ClockWise2Icon'
export { default as ClockIcon } from './dashboard/my-ads/ClockIcon'
// new ads
export { default as IconPercent } from './new-ads/percent-icon'
export { default as IconArrow } from './new-ads/icon-arrow'
export { default as IconPan } from './new-ads/icon-pan'
export { default as IconTarget } from './new-ads/icon-target'
export { default as IconPhone } from './new-ads/icon-phone'
export { default as FinalCostBg } from './new-ads/final-cost-bg'
export { default as CalculateBg } from './new-ads/calculate-bg'
// dashboard >>> notifications
export { default as IconPencil } from './dashboard/notifications/icon-pencil'
// dashboard >>> comments
export { default as IconReply } from './dashboard/comments/icon-reply'
export { default as IconThumb } from './dashboard/comments/icon-thumb'
// dashboard >>> bookings history
export { default as IconPrinter } from './dashboard/bookings-history/icon-printer'
export { default as PicPayment } from './dashboard/bookings-history/pic-payment'
// Dashboard >>> support
export { default as BgSupport } from './dashboard/support/bg-support'
export { default as IconSupport } from './dashboard/support/icon-support'
// Dashboard >>> connect booking
export { default as IconSimpleTick } from './dashboard/connect-booking/icon-simple-tick'
// Dashboard >>> offers
export { default as IconCopy } from './dashboard/offers/icon-copy'
// single
export { default as IconMiniPicture } from './single/icon-mini-picture'
export { default as IconFlag } from './single/icon-flag'
export { default as IconShare } from './single/icon-share'
export { default as IconHeart } from './single/icon-heart'
export { default as IconRingingBell } from './single/icon-ringing-bell'
export { default as IconSharpStar } from './single/icon-sharp-star'
export { default as IconLike2 } from './single/icon-like-2'
// single >>> payment methods
export { default as IconVisa } from './single/payment-methods/icon-visa'
export { default as IconPaypal } from './single/payment-methods/icon-visa'
export { default as IconColoredPayment } from './single/payment-methods/icon-colored-payment'
// single >>> emojis
export { default as IconAngryFace } from './single/emojis/icon-angry-face'
export { default as IconPokerFace } from './single/emojis/icon-poker-face'
export { default as IconHappyFace } from './single/emojis/icon-happy-face'
export { default as IconLovingFace } from './single/emojis/icon-loving-face'
export { default as IconStarryFace } from './single/emojis/icon-starry-face'
// single >>> location
export { default as IconPhoneBook } from './single/location/icon-phone-book'
export { default as IconPhone2 } from './single/location/icon-phone2'