import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Footer from "@/sections/footer/Footer";
import Menu from "@/sections/home/header/menu";
import { NextIntlClientProvider } from 'next-intl'
import { getMessages } from 'next-intl/server'

const geistSans = localFont({
  src: "../../assets/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "../../assets/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}

export async function generateStaticParams() {
  return [{ lang: 'fa' }, { lang: 'en' }];
}

export default async function RootLayout({
  children,
  params: { locale },
}: RootLayoutProps) {
  const messages = await getMessages()
  return (
    <NextIntlClientProvider messages={messages}>
    <html lang={locale}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <Menu/>
          {children}
          <Footer />
      </body>
    </html>
    </NextIntlClientProvider>
  );
}