import type { Metadata } from "next";
import "@/assets/css/globals.css";
import Footer from "@/sections/footer/Footer";
import Menu from "@/sections/home/header/menu";
import { NextIntlClientProvider } from 'next-intl'
import { getMessages } from 'next-intl/server'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}

export async function generateStaticParams() {
  return [{ lang: 'fa' }, { lang: 'en' }];
}

export default async function RootLayout({
  children,
  params: { locale },
}: RootLayoutProps) {
  const messages = await getMessages()
  return (
    <NextIntlClientProvider messages={messages}>
    <html lang={locale}>
      <body>
          <Menu/>
          {children}
          <Footer />
      </body>
    </html>
    </NextIntlClientProvider>
  );
}